# Generated by Django 2.2.10 on 2021-02-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
    ]
